export const textBoxes = [
  { text: "Finetuned LLMs", emoji: "🧠" },
  { text: "AI orchestrations", emoji: "🎭" },
  { text: "Research agents", emoji: "🔬" },
  { text: "Desktop apps", emoji: "🖥️" },
  { text: "Voice agents", emoji: "🗣️" },
  { text: "Mobile apps", emoji: "📱" },
  { text: "Websites", emoji: "🌐" },
  { text: "Chatbots", emoji: "💬" },
  { text: "Scrapers", emoji: "🦋" },
  { text: "Visualizations", emoji: "📊" },
  { text: "Finetuned diffusion models", emoji: "🎨" },
  { text: "Computer vision tools", emoji: "👁️‍🗨️" },
  { text: "Payment integrations", emoji: "💳" },
  { text: "Recommendation engines", emoji: "🔮" },
  { text: "Real-time dashboards", emoji: "📈" },
  { text: "Web games", emoji: "🎮" },
  { text: "CMS", emoji: "📚" },
  { text: "Data pipelines", emoji: "🌊" },
  { text: "Synthetic data", emoji: "🧪" },
  { text: "Knowledge graphs", emoji: "🌈" },
  { text: "E-commerce platforms", emoji: "🛍️" },
  { text: "Model evals", emoji: "✨" },
  { text: "LLM-powered search systems", emoji: "🔎" },
  { text: "Multimodal AI assistants", emoji: "🤖" },
  { text: "Prompt engineering tools", emoji: "🛠️" },
  { text: "Mobile games", emoji: "📲" },
  { text: "Automated test suites", emoji: "🧬" },
  { text: "Social networks", emoji: "🌐" },
  { text: "Video processors", emoji: "📽️" },
  { text: "Audio systems", emoji: "🔊" },
  { text: "Geospatial applications", emoji: "🌏" },
];
